name: Main

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 4.0.0

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: ./dvdservice

      - name: Run docker-compose
        working-directory: ./dvdservice
        run: docker-compose up -d

      - name: Package with Maven (skip tests)
        working-directory: ./dvdservice
        run: mvn install -DskipTests --no-transfer-progress

      - name: Start the application
        working-directory: ./dvdservice
        run: java -jar target/*.jar &

      - name: Wait for the service
        timeout-minutes: 1
        run: |
          echo "Waiting for app to be available..."
          for i in {1..10}; do
            nc -z localhost 8080 && echo "App is up!" && exit 0
            sleep 6
          done
          echo "App not available!" && exit 1

      - name: Run tests
        working-directory: ./dvdservice
        run: mvn test --no-transfer-progress
